" My (Leo Yan) vimrc file.

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set nobackup			" do not keep a backup file, use versions instead
set history=50			" keep 50 lines of command line history
set ruler			" show the cursor position all the time
set showcmd			" display incomplete commands
set incsearch			" do incremental searching
set nu				" show number

set autoindent			" auto indentation
set noexpandtab			" do not expand tab as spaces
set tabstop=8			" set tab as 8-chars width
set cindent shiftwidth=8	" enable C-language indentation

" Set character encoding and file encodings
if has("multi_byte")
    set encoding=utf-8
    set formatoptions+=mM
    set fencs=utf-8,gbk

    if v:lang =~? '^\(zh\)\|\(ja\)\|\(ko\)'
        set ambiwidth=double
    endif
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Filetype specific rules
augroup file_spec_format
    autocmd!

    filetype plugin indent on	" enable file type detection

    " For all text and markdown files set 'textwidth' to 78 characters.
    autocmd FileType text setlocal textwidth=78
    autocmd FileType md setlocal textwidth=78

    " enables spell checking for Git commit messages.
    autocmd Filetype gitcommit setlocal spell spelllang=en_us

    " Disables wrapping for Org files.
    autocmd bufreadpre *.org setlocal textwidth=0

    " Restore last cursor position on file open.
    " Don't do it when the position is invalid or when inside an event handler
    " (happens when dropping a file on gvim).
    autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal g`\"" |
      \ endif
augroup END

" Highlight for columns 78–80 (warning) and columns > 80 (error)
augroup c_width_check
    autocmd!
    autocmd BufWinEnter *.c,*.h,*.S,*.s let w:m1=matchadd('Search', '\%<81v.\%>77v', -1)
    autocmd BufWinEnter *.c,*.h,*.S,*.s let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
augroup END

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen

augroup extra_whitespace
    autocmd!
    " Re-apply highlight after :colorscheme
    autocmd ColorScheme * highlight default ExtraWhitespace ctermbg=darkgreen guibg=darkgreen

    " Apply/refresh per-window matches
    autocmd BufWinEnter * call s:ExtraWhitespaceMatch(0)
    autocmd InsertEnter * call s:ExtraWhitespaceMatch(1)
    autocmd InsertLeave * call s:ExtraWhitespaceMatch(0)

    " Clean up window-local match on leave
    autocmd BufWinLeave * call s:ExtraWhitespaceClear()
augroup END

function! s:ExtraWhitespaceSkip() abort
    " Skip special buffers (netrw, help, terminals, etc.)
    if &buftype !=# '' | return 1 | endif
    if &filetype ==# 'netrw' | return 1 | endif
    return 0
endfunction

function! s:ExtraWhitespaceClear() abort
    if exists('w:extra_ws_match_id')
	" ID may already be gone if another plugin/netrw cleared matches
        silent! call matchdelete(w:extra_ws_match_id)
        unlet w:extra_ws_match_id
    endif
endfunction

function! s:ExtraWhitespaceMatch(in_insert) abort
    if s:ExtraWhitespaceSkip()
        return
    endif

    call s:ExtraWhitespaceClear()

    let l:pat = a:in_insert ? '\s\+\%#\@<!$' : '\s\+$'
    let w:extra_ws_match_id = matchadd('ExtraWhitespace', l:pat)
endfunction

if exists(':MiniBufExplorer') || exists('g:loaded_minibufexpl') || globpath(&rtp, 'plugin/minibufexpl.vim') != ''
    " Enable window navigation mappings inside miniBufExplorer
    let g:miniBufExplMapWindowNavVim    = 1   " Use <C-h/j/k/l> to move between windows
    let g:miniBufExplMapWindowNavArrows = 1   " Use arrow keys to move between windows
    let g:miniBufExplMapCTabSwitchBufs  = 1   " <C-Tab>/<C-S-Tab> cycle buffers (if supported)
    let g:miniBufExplModSelTarget       = 1   " Prefer target window for modified buffer selection
    let g:miniBufExplMaxSize            = 2   " Limit explorer height
endif

" Keep Taglist in sync when buffers are closed/switched
augroup taglist_autoclean
    autocmd!
    " Refresh when switching buffers (covers most cases)
    autocmd BufEnter * if exists(':TlistUpdate') | silent! TlistUpdate | endif
    " Refresh again when a buffer is deleted/wiped out (your case)
    autocmd BufDelete,BufWipeout * if exists(':TlistUpdate') | silent! TlistUpdate | endif
augroup END

" Force ctags to parse as C (useful if your code is mostly C / kernel)
let Tlist_Ctags_Cmd                 = 'ctags --language-force=C'
let Tlist_Inc_Winwidth              = 0   " Do not auto-resize Taglist window
let Tlist_Exit_OnlyWindow           = 1   " If Taglist is the only window, quit Vim
let Tlist_File_Fold_Auto_Close      = 1   " Auto-close folds for non-current files
let Tlist_Process_File_Always       = 1   " Always (re)generate tags when entering buffer
let Tlist_Enable_Fold_Column        = 0   " Hide fold column in Taglist window
let Tlist_Show_One_File             = 1   " Show tags only for current file

" Only define defaults if the user has not overridden them
if !exists('g:utl_cfg_hdl_scm_http')
    " Use xdg-open if available (common on Linux systems)
    let g:utl_cfg_hdl_scm_http_system   = 'silent! !xdg-open %u'
    let g:utl_cfg_hdl_scm_http          = g:utl_cfg_hdl_scm_http_system
endif

if exists('g:loaded_vimtex')
    let g:tex_flavor = 'latex'

    " PDF viewer (Linux example: zathura)
    if executable('zathura')
        let g:latex_view_general_viewer = 'zathura'
        let g:vimtex_view_method        = 'zathura'
    endif
    " macOS alternative:
    " let g:vimtex_view_method = 'skim'

    " Quickfix behavior
    let g:vimtex_quickfix_open_on_warning = 0
    let g:vimtex_quickfix_mode            = 2

    " Optional latexmk config (kept commented; enable if you need it)
    " let g:vimtex_compiler_latexmk = {
    "       \ 'build_dir' : '',
    "       \ 'callback' : 1,
    "       \ 'continuous' : 1,
    "       \ 'executable' : 'latexmk',
    "       \ 'hooks' : [],
    "       \ 'options' : [
    "       \   '-verbose',
    "       \   '-file-line-error',
    "       \   '-synctex=1',
    "       \   '-interaction=nonstopmode',
    "       \   '-pdf',
    "       \ ],
    "       \}
    "
    " let g:vimtex_compiler_latexmk_engines = {
    "       \ '_'                : '-pdf',
    "       \ 'pdflatex'         : '-pdf',
    "       \ 'dvipdfex'         : '-pdfdvi',
    "       \ 'lualatex'         : '-lualatex',
    "       \ 'xelatex'          : '-xelatex',
    "       \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
    "       \ 'context (luatex)' : '-pdf -pdflatex=context',
    "       \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
    "       \}
endif

augroup mutt_mail
    autocmd!
    " Apply mail-friendly settings to mutt temp files
    autocmd BufNewFile,BufRead /tmp/mutt*,$HOME/tmp/mutt* call s:mutt_settings()
augroup END

function! s:mutt_settings() abort
    setlocal noautoindent
    setlocal filetype=mail
    setlocal wrapmargin=0
    setlocal textwidth=78
    setlocal nonumber
    setlocal digraph
    setlocal nolist
endfunction

" netrw (built-in file browser) settings
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_winsize = 50
let g:netrw_altv = 1
let g:netrw_alto = 1

"set termguicolors
let g:solarized_termcolors=256
"let g:solarized_style="light"
let g:solarized_diffmode="normal"
let g:solarized_contrast="normal"
let g:solarized_visibility="flat"
let g:solarized_use16=1
"let g:solarized_italics=1
set background=dark
colorscheme solarized8

" Insert Reviewed-by / Tested-by tags
function! s:InsertTag(line) abort
   " Append a new line below the cursor without clobbering registers/history
   call append(line('.'), a:line)
endfunction

function! s:ReviewTag() abort
   call s:InsertTag('Reviewed-by: Leo Yan <leo.yan@arm.com>')
endfunction

function! s:TestTag() abort
   call s:InsertTag('Tested-by: Leo Yan <leo.yan@arm.com>')
endfunction

" Normal mode mappings
nnoremap <silent> <F11> :call <SID>ReviewTag()<CR>
nnoremap <silent> <F12> :call <SID>TestTag()<CR>

" Insert mode mappings (return to insert where you were)
inoremap <silent> <F11> <C-o>:call <SID>ReviewTag()<CR>
inoremap <silent> <F12> <C-o>:call <SID>TestTag()<CR>

" Toggle Taglist (normal mode)
nnoremap <silent> <F8> :TlistToggle<CR>

" Replace Ex mode with text formatting (use Q as gq)
nnoremap Q gq
vnoremap Q gq

" In insert mode, make <C-d> delete forward (like <Del>)
inoremap <C-d> <Del>

" Open netrw file explorer (normal mode)
nnoremap <silent> <C-E> :Lexplore<CR>

call plug#begin()
Plug 'yegappan/taglist'
Plug 'dr-kino/cscope-maps'
Plug 'jceb/vim-orgmode'
Plug 'tpope/vim-speeddating'
Plug 'inkarkat/vim-SyntaxRange'
Plug 'vimwiki/vimwiki'
Plug 'lervag/vimtex'
call plug#end()
