(function(){var g=void 0,h=true,i=null,l=false,m,n=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ca(){}
function ea(a,b,c){switch(typeof b){case "string":fa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),ea(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),fa(e,c),c.push(":"),ea(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ga={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ha=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function fa(a,b){b.push('"',a.replace(ha,function(a){if(a in ga)return ga[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return ga[a]=e+b.toString(16)}),'"')};var ia={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ja={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function ka(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function p(a,b){var c="",d=la(encodeURIComponent(a));d.splice(b||5,d.length);q(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function la(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,o=3285377520,k=[],j,u,y,J,K,da=Math.ceil((a.length/4+2)/16),V=[da],z=0,w;z<da;z++){V[z]=[];for(j=0;j<16;j++)V[z][j]=a.charCodeAt(z*64+j*4)<<24|a.charCodeAt(z*64+j*4+1)<<16|a.charCodeAt(z*64+j*4+2)<<8|a.charCodeAt(z*64+j*4+3)}z=(a.length-1)*8;a=da-1;V[a][14]=Math.floor(z/Math.pow(2,32));V[a][15]=z&4294967295;for(z=0;z<da;z++){for(w=0;w<16;w++)k[w]=V[z][w];
for(w=16;w<80;w++)k[w]=(k[w-3]^k[w-8]^k[w-14]^k[w-16])<<1|(k[w-3]^k[w-8]^k[w-14]^k[w-16])>>>31;a=c;j=d;u=e;y=f;J=o;for(w=0;w<80;w++)K=Math.floor(w/20),K=(a<<5|a>>>27)+(K==0?j&u^~j&y:K==1?j^u^y:K==2?j&u^j&y^u&y:j^u^y)+J+b[K]+k[w]&4294967295,J=y,y=u,u=j<<30|j>>>2,j=a,a=K;c=c+a&4294967295;d=d+j&4294967295;e=e+u&4294967295;f=f+y&4294967295;o=o+J&4294967295}return[c,d,e,f,o]}
function ma(a){var b=n.navigator,c=n.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];q(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=n.performance;d=d.concat([b&&b.now?b.now():"",document.title,n.location.href,r(),ka()]);return d.concat(a||[]).join()}function s(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function t(a){return typeof a!=="undefined"}function na(a){return a.replace(/^www\./,"")}function v(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function oa(a,b){var c=n;c.removeEventListener?c.removeEventListener(a,b,l):c.detachEvent&&c.detachEvent("on"+a,b)}function x(a){return typeof a==="number"}function A(a){return typeof a==="string"}function pa(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function r(){return(new Date).getTime()}function qa(){return n.location.protocol==="https:"?"https:":"http:"}function q(a,b){if((!!a&&a.constructor===Object)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===l)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===l)break}}function ra(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}
function sa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,o=a.length;f<=o;f++)c[0][f]=f;for(var k,j,u,d=1;d<=e;d++)for(f=1;f<=o;f++)k=d-1,j=f-1,u=c[k][j],b.charAt(k)==a.charAt(j)?c[d][f]=u:(j=c[d][j]+1,k=c[k][f]+1,u+=2,c[d][f]=Math.min(j,k,u));return c[b.length][a.length]}var ta,ua=n.setInterval,va=n.clearInterval,wa=n.setTimeout,B=n.clearTimeout;
function xa(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function ya(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c){var d,e;d=d||"*";e=e||document;if("querySelectorAll"in e)c=e.querySelectorAll(d+"[data-cb-scroll-element]");else{c=[];d=e.getElementsByTagName(d);for(e=d.length;e--;)d[e].getAttribute("data-cb-scroll-element")&&c.push(d[e])}if(c&&c.length)return c[0][b]}if(x(n[a]))return n[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}
function za(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function C(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}
function Aa(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var d=a.ownerDocument.documentElement,e=0,f=t(c)?c+1:-1;A(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function Ba(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Ca(a){a=a||window.event;return!a?i:Aa(a.target||a.srcElement,Ba,10)}function Da(a,b){var c=document.createElement(a);q(b,function(a,b){c.setAttribute(b,a)});return c};function Ea(){this.G={};this.Ra=1}function D(a,b,c,d){a.Ra++;a.G[b]=a.G[b]||{};a.G[b][a.Ra]=[c,d];return a.Ra}function E(a,b){if(A(b))a.G[b]=g,delete a.G[b];else if(x(b)){var c=h;q(a.G,function(a){q(a,function(e,f){if(parseInt(f,10)===b)return a[f]=g,delete a[f],c=l});return c})}}Ea.prototype.O=function(a,b){if(this.G[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];q(this.G[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
Ea.prototype.addEventListener=function(a,b){var c=D(this,a,b);b._cbEventId=c};Ea.prototype.removeEventListener=function(a,b){this.G[a]&&this.G[a][b._cbEventId]&&this.G[a][b._cbEventId][0]===b&&E(this,b._cbEventId)};var F=new Ea,Fa="a";var G={};
G.q=function(){G.Ea?G.oa("pageload"):(G.lb=[{target:n,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:n,event:"resize"},{target:document.body,event:"mousedown"}],G.va=i,G.T=i,G.Da={},G.Ca={},G.ab={},G.wa={},q(G.lb,function(a){var b=a.event;v(a.target,b,function(a){G.oa.call(G,b,a)})}),D(F,"f",function(){G.oa("focus")}),G.oa("pageload"),v(document.body,"click",function(a){(a=Ca(a))&&F.O("c",a)},h),v(document.body,"contextmenu",function(a){(a=Ca(a))&&
F.O("r",a)}),G.Ea=h)};G.sb=function(){var a,b=G.ab.keydown;if(b===g)return l;b=r()-b;return b<=(a||15E3)&&b>=0};G.ea=function(a,b){var c=G.wa[a];if(!c)return"";var b=b||r(),d,e=0;q(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};G.Rb=function(){G.wa={}};G.Va=100;
G.oa=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.Xb(a);if(G.va===i)G.jb(a);else if(!G.T||ia[G.T]<ia[a]||ja[G.T]<ja[a])G.T=a};G.Xb=function(a){var b=r();G.ab[a]=b;var c=G.wa[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();G.wa[a]=c};G.jb=function(a){G.va=wa(G.wb,G.Va);F.O(Fa);G.Da[a]!==i&&B(G.Da[a]);G.Ca[a]!==i&&B(G.Ca[a]);G.ib(a,G.Da,ia,"i");G.ib(a,G.Ca,ja,"j")};
G.ib=function(a,b,c,d){b[a]=wa(function(){B(b[a]);delete b[a];var c=l;q(b,function(){c=h;return l});c||F.O(d)},c[a]+G.Va)};G.wb=function(){B(G.va);G.va=i;if(G.T)G.jb(G.T),G.T=i};var Ga,Ha,H,Ia,Ja;(function(){var a,b;q(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof n.document[a]==="boolean")return b=c,l});b!==g&&(Ia=a,Ja=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),H=b+"visibilitychange")})();var I=l;function Ka(){I=Ja&&n.document[Ja]==="prerender"?h:l}function La(){Ha=h;F.O("f")}function Ma(){Ha=l;F.O("b")}
function Na(a,b,c){n.addEventListener?n.addEventListener(a,c,l):n.document.attachEvent&&n.document.attachEvent(b,c)}function Oa(){var a=h;n.document.hasFocus&&(a=n.document.hasFocus());var b=l;Ia&&(b=n.document[Ia]);return a&&!b}function Pa(){Oa()?La():Ma()}function Qa(a){Ka();if(I){var b=l,c=function(){b||(Ka(),I||(b=h,a(),n.window.setTimeout(function(){n.document.removeEventListener(H,c,l)},100)))};n.document.addEventListener(H,c,l)}else a()};function L(){this.a=n._sf_async_config||{};this.Wa=s(this.fb,this)}L.prototype.q=function(){this.gb=0};L.prototype.fb=function(){};L.prototype.sa=function(a){if(!I){var b=this.Wa,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};L.prototype.ca=function(){this.Wa=i};function Ra(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),q(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Sa(a,b){var c="",d=n.location.href.split("?");if(d.length){var d=Ra(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function Ta(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Ua(a){var b=[];q(Va,function(c){var d=a[c];t(d)&&(Object.prototype.toString.call(d)==="[object Array]"?q(d,function(a){b.push(c+"="+a)}):d&&d.constructor===Object?q(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function Wa(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=n.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=Ta(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Ta(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Xa(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function M(a,b,c){a[b]=a[b]||c}function Ya(a,b){for(var c=n[a]||[];c.length;)b(c.shift());n[a]={push:b}}function Za(a){q(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Ra(b.src.split("?")[1]),M(a,"uid",b.uid),M(a,"domain",b.domain),l})}function N(a,b){return a[b]?encodeURIComponent(a[b]):""}function $a(a){var b={};q(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};var O={};O.vb=function(){try{O.create("_cb_test","1",1);var a=O.k("_cb_test");O.remove("_cb_test");return a==="1"}catch(b){return l}};O.k=function(a){a+="=";var b="";q(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),l});return b};
O.create=function(a,b,c){var d=n._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(r()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};O.remove=function(a){return O.k(a)?O.create(a,"",-86400):""};var P={};P.B=function(a){var b=n._sf_async_config;if(!a&&b&&b.noCookies)return i;if(P.B.Aa!==g)return P.B.Aa;var a=r()+"",c,d;try{if((d=n.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return P.B.Aa=d}catch(e){}return P.B.Aa=i};P.k=function(a){var b=P.B();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&r()>c)?(P.remove(a),""):b.getItem(a)||""};
P.create=function(a,b,c){var d=P.B();if(d){var e=new Date;e.setTime(r()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};P.remove=function(a){var b=P.B();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function ab(a){this.ra=a||"";this.xb=P.B()!==i||O.vb();this.Qa=l;bb(this)}m=ab.prototype;m.isSupported=function(){return this.xb};
function bb(a){if(!O.k("_cb_ls")){var b=P.B()!==i,c=O.k("_SUPERFLY_lockout");c&&q(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,h)});var d=O.k("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,h),O.remove("_chartbeat3"));b&&((b=O.k("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,h),(b=O.k("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,34128E3,h),(b=O.k("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));O.create("_cb_ls","1",34128E3)}}
m.create=function(a,b,c,d){a=d?a:this.ra+a;(P.B()?P:O).create(a,b,c);P.B()&&O.create(a,b,c)};m.update=function(a,b,c,d,e,f,o){a=d?a:this.ra+a;e=A(e)?e:"::";d=(d=this.k(a,h))?d.split(e):[];if(o&&d.length){var k=o(b),j=ra(d,function(a){return o(a)===k});j!==-1&&d.splice(j,1)}d.push(b);for(x(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,h)};
m.k=function(a,b){var a=b?a:this.ra+a,c=(P.B()?P:O).k(a);if(!c&&P.B()&&(c=O.k(a))&&O.k("_cb_ls")){this.Qa=h;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}P.create(a,c,d)}return c};m.remove=function(a,b){a=b?a:this.ra+a;(P.B()?P:O).remove(a);P.B()&&O.remove(a)};function cb(a){var b=i;if(a&&(b=db()))return b;var c=n.location,b=Q(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function db(){var a=i;q(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Wa(b.href),a=Q(b.pathname)+b.search+b.hash,l});return a}
for(var eb={},fb=0;fb<81;fb++)eb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(fb)]=h;function gb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return eb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Q(a){if(!A(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,gb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function R(a,b){var c=S();return t(b)&&!t(c[a])?b:c[a]}function S(){t(n._cb_shared)||(n._cb_shared={});return n._cb_shared};var T={ob:{IDLE:0,nb:1,mb:2,xa:3},pb:{IDLE:0,nb:1,mb:2,xa:3},H:0,J:0};T.q=function(){if(!T.Ea)D(F,Fa,T.Eb,T),D(F,"i",T.Ib,T),D(F,"f",T.Gb,T),D(F,"b",T.Fb,T),D(F,"j",T.Hb,T),T.Ea=h};T.Bb=function(){return T.H};T.Cb=function(){return T.J};T.Eb=function(){T.H===1?T.Q(3):T.H===0&&T.Q(2);T.J===1?T.P(3):T.J===0&&T.P(2)};T.Ib=function(){T.H===3?T.Q(1):T.H===2&&T.Q(0)};T.Hb=function(){T.J===3?T.P(1):T.J===2&&T.P(0)};T.Gb=function(){(T.H===0||T.H===2)&&T.Q(3);(T.J===0||T.J===2)&&T.P(3)};
T.Fb=function(){T.H===3?T.Q(2):T.H===1&&T.Q(0);T.J===3?T.P(2):T.J===1&&T.P(0)};T.Q=function(a){T.H=a;F.O("s",a)};T.P=function(a){T.J=a;F.O("x",a)};function hb(a,b){this.Ba=a||g;this.Ha=b||g;this.Z=this.N=0;this.Za=s(this.Lb,this);this.Pa=this.M=i}m=hb.prototype;m.q=function(){this.Z=this.N=0;this.M=i;this.Pa=D(F,"s",this.fa,this);this.fa(T.Bb())};m.fa=function(a){va(this.M);this.M=i;if(a===T.ob.xa)this.M=ua(this.Za,1E3)};m.Lb=function(){if(this.Ba===g||this.Ba())this.N++,this.Z++,this.Ha&&this.Ha()};m.terminate=function(){va(this.M);this.M=i;E(F,this.Pa)};m.ca=function(){this.terminate();this.Ha=this.Ba=g};function ib(a,b){hb.call(this,a,b)}ba(ib,hb);ib.prototype.q=function(){this.Z=this.N=0;this.M=i;this.Pa=D(F,"x",this.fa,this);this.fa(T.Cb())};ib.prototype.fa=function(a){va(this.M);this.M=i;if(a===T.pb.xa)this.M=ua(this.Za,1E3)};function U(){L.call(this);this.X=[];this.D=new ab(this.Ub);this.D.remove("_SUPERFLY_nosample");this.F=new hb;this.U=new ib;this.Ia=s(this.qa,this);v(n,"unload",this.Ia);Qa(s(this.q,this))}ba(U,L);m=U.prototype;m.Ma=h;
m.q=function(){U.S.q.call(this);this.ma=this.$=0;this.ba=r();this.La=p(jb(this));this.Ka=h;this.Fa=72E5;if(this.Ma){var a=+this.a.sessionLength;if(!isNaN(a))this.Fa=a*6E4}a=R("d");if(!a){var a=[],b=this.D.k("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>5&&(a=[]);var b=r(),c=this.D.k("_cb",h);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),e=b-+(a[2]||0);S().n=c&&d>18E5&&e<2592E6?0:1;d=a[4];if(!d||e>18E5)d=p(jb(this)),a[4]=d;var d="1",f=a&&+a[2],e=a&&a[3];if(a&&f&&e)if(d=Math.abs((pa(b)-
pa(f))/864E5)){d=Math.min(d,16)-1;for(f="";d--;)f+=0;d=(e+f+"1").slice(-16)}else d=e;e=d;c||(c=this.a.utoken||p(jb(this),3),a[1]=b);a[2]=b;a[3]=e;this.a.utoken=this.ka;this.D.create("_cb",c,34128E3,h);this.D.create("_chartbeat2",a.join("."),34128E3,h);a[0]=c;S().d=a}this.hc=a.join(".");var o;c=+a[1];e=+a[2];if((b=a[3])&&c&&e)o=(Math.min((Math.abs((pa(e)-pa(c))/864E5)||0)+1,16,b.length)-1).toString(16),o+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Ya=o;this.Nb=R("n",1);this.ka=a[0];this.Tb=
a[4];this.F.q();this.U.q();T.q();G.q();Ga||(Ha=Oa(),H&&n.document.addEventListener&&n.document.addEventListener(H,Pa,l),Na("focus","onfocusin",La),Na("blur","onfocusout",Ma),Ha&&La(),Ga=h);this.ha=0;this.rb=D(F,Fa,this.Ob,this)};function kb(a){if(!a.D.k("_SUPERFLY_lockout")&&!I)a.Mb?a.ta():(a.Mb=h,!n._sf_async_config&&!n._cbq?(a.pa=s(a.ta,a),v(n,"load",a.pa)):a.ta())}m.ta=function(){var a=n._sf_startpt,b=n._sf_endpt;if(x(a))this.Ja=x(b)?b-a:r()-a;G.q();a=s(this.ia,this);this.$a=ua(a,15E3);this.ia()};
m.ia=function(){var a=this.F.Z,a=this.a.reading&&+this.a.reading||a>0;if(this.ma<this.$&&!a)this.ma++;else{var b;if(ta===g)b=n.navigator.userAgent,ta=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=ta;b&&!a?this.ma++:(a?this.$=0:lb(this),this.ma=0,this.X.push(0),this.X.length>18&&this.X.shift(),this.Ma&&r()-this.ba>=this.Fa?this.terminate():this.ja())}};
m.fb=function(){this.X.push(1);var a=0;q(this.X,function(b){a+=b});a<3?(this.Ka=h,lb(this)):(this.terminate(),this.D.create("_SUPERFLY_lockout","1",600))};m.qa=function(){};m.Ob=function(){var a=mb(this);this.ha=Math.max(this.ha,a)};function mb(a){return Math.floor(ya("Y","Top",!!a.a.scrollElement))}function lb(a){var b=a.$,b=b?Math.min(b*2,16):1;a.$=b}m.la=function(){this.qa();this.terminate()};m.kb=function(){this.q();kb(this)};
function nb(a){if(a.a.virtualReferrer)return h;a=(document.referrer||"").indexOf("://"+n.location.hostname+"/");return a!=-1&&a<9}function ob(a){a=a.a.virtualReferrer;if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Wa(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Q(b.pathname),a=Xa(b)}return encodeURIComponent(a)}function pb(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}function jb(a){a=[ob(a),C("Width"),C("Height")];return ma(a)}
function qb(a){var b=[],c=a.D.k("_chartbeat4");c&&(q(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.D.remove("_chartbeat4"));return b}m.terminate=function(){this.F.terminate();this.U.terminate();E(F,this.rb);this.pa!==g&&oa("load",this.pa);va(this.$a);S().d=g;S().n=g};m.ca=function(){this.terminate();oa("unload",this.Ia);this.Ia=this.pa=this.D=this.X=this.a=i;this.F.ca();this.F=i;this.U.ca();this.U=i;U.S.ca.call(this)};function rb(a){for(var b=R("m")||[];b.length;)a(b.shift());a={push:a};S().m=a};function sb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=tb(a);d+=f.x;e+=f.y;for(var o=l,k=c?0:Math.floor(ya("X","Left",g)),j=c?0:Math.floor(ya("Y","Top",g)),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=tb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(ub(a,["position"]).position==="fixed"){o=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:k,e-=b?b.scrollTop:j);o&&(d+=k,e+=j);return{x:d,y:e}}
function ub(a,b){var c={},d,e;n.getComputedStyle?d=n.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");q(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var vb=/matrix(3d)?\((.*)\)/;function tb(a){var b={x:0,y:0},a=ub(a,["transform"]).transform;if(!A(a))return b;var c=a.match(vb);if(!c)return b;var a=c[2].split(", "),d;t(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function wb(){var a=n.location.href,a=a.replace(/-{2,}/g,"-"),a=Wa(a);a.pathname=Q(a.pathname);return a}
function xb(a){var b=O.k("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=wb(),o=Xa(f);q(b,function(a,b){var f=a.split(","),j=sa(o,decodeURIComponent(f[0]));if(j===0)return c=f,d=b,l;if(e===g||j<e)e=j,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+yb(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),k=c[2];c.splice(0,3);for(var j=c.length/2,u=0;u<j;u++)a.push({fc:b,origin:f,aa:k,yb:c[u*2],Yb:c[u*2+1]});
return a}function yb(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.cb&&(c=new Date,c.setTime(c.getTime()+a.cb),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function zb(a){var b=a.topStorageDomain,a=a.domain,c=n.location.hostname;return b?b:Ab(c,a)?a:c.replace(/^www\./,"")}function Ab(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return l;if(c.pop()!==d.pop())return l}return h}
function Bb(a,b,c,d){this.Ab=a;this.zb=b;this.Zb=c;this.aa=d};function Cb(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,o,k,j,u,y,J;f&&f!==c;){o=f.nodeName.toLowerCase();e=f;k=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){j=f.children;u=0;for(y=0,J=j.length;y<J;y++){if(e===j[y]){o+="["+(1+y-u)+"]";break}j[y].nodeName!==k&&u++}}d.unshift(o)}return d.join("/")};function W(){this.Ub="_t_";U.call(this)}ba(W,U);m=W.prototype;
m.q=function(){W.S.q.call(this);Za(this.a);var a=n.location;M(this.a,"mabServer","mabping.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);M(this.a,"path",cb(!!this.a.useCanonical));this.ga=na(a.hostname);this.a.domain=na(this.a.domain);this.Wb=zb(this.a);this.da=this.na=l;this.Xa=[];var b=this,a=xb({domain:"."+this.Wb,cb:6E4,path:"/"});if(a!==i)this.na=h,q(a,function(a){b.Xa.push(new Bb(a.origin,a.yb,a.Yb,a.aa))});this.eb=0;this.ua=i;rb(s(this.Kb,this))};
m.ja=function(){var a=this.F.N,b=Db(this),c,d=this;this.na&&q(this.Xa,function(e){c=b+"&x="+e.zb+"&v="+e.Zb+"&ml="+e.aa+"&xo="+e.Ab+"&e="+a;d.sa(c)});!this.da&&this.ua&&Eb(this,this.ua);this.da=h};m.ta=function(){var a=n._sf_startpt,b=n._sf_endpt;if(x(a))this.Ja=x(b)?b-a:r()-a;G.q();if(this.na)a=s(this.ia,this),this.$a=ua(a,500);this.ia()};m.ia=function(){var a,b;this.da?(a=this.F.N,b=this.eb*15,a-b>=15&&(this.ja(),this.eb+=1),a>=45&&this.terminate()):this.ja()};
function Db(a){var b=a.a;return qa()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ga)+"&u="+a.ka+"&c="+Math.round((r()-a.ba)/600)/100}m.qa=function(){};m.Vb=function(a){var b=a.d,c=i;b!==i&&(c={Na:b.s,aa:b.g,bb:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.da?Eb(this,a):this.ua=a};
function Eb(a,b){var c=Db(a),d=b.status,e=b.data;if(d=="s"&&e!==i){var f=s(a.sa,a);e.Na&&e.Na.constructor===Object&&q(e.Na,function(a,b){f(c+"&x="+b+"&v="+a+"&ml="+e.aa+"&e=-1")});Object.prototype.toString.call(e.bb)==="[object Array]"&&q(e.bb,function(a){f(c+"&me=3&ml="+e.aa+"&x="+a)})}else d=="e"&&a.sa(c+"&me="+b.code)}m.Kb=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.Vb.apply(this,a):e==="v"&&this.Sb.apply(this,a)}};
m.la=function(){S().m=[];t(this.Sa)&&this.Sa();W.S.la.call(this)};m.Sb=function(a){this.Sa=a};m.terminate=function(){this.Sa=this.gc=g;this.ua=i;this.da=this.na=g;W.S.terminate.call(this)};if(!n.pSUPERFLY_mab){var Fb=new W,Gb={};Gb.evps=s(Fb.la,Fb);Gb.svps=s(Fb.kb,Fb);n.pSUPERFLY_mab=Gb;kb(Fb)};var Hb="engagedSeconds",Ib={dc:"id",cc:Hb,$b:"campaignId",ac:"creativeId",ec:"placementId",bc:"element"};var Jb,Kb,X;
function Lb(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);Mb();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=t(g)?g:{},b.src=a,a=Da("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],t(g)?g.appendChild(a):b&&b.appendChild(a)}}
function Mb(){B(Kb);Kb=g;oa("message",Lb);X&&X.parentNode&&X.parentNode.removeChild(X);X=g};function Nb(){var a=n._sf_async_config&&n._sf_async_config.domain;if(a&&!Jb){Jb=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);v(n,"message",Lb);Kb=wa(Mb,1E4);var b=t(g)?g:{};b.src=a;a=Da("iframe",b);a.style.display="none";t(g)?g.appendChild(a):document.body&&document.body.appendChild(a);X=a}}
function Ob(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=P.B(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Nb(),oa("message",Ob))}};function Y(){"postMessage"in window&&v(n,"message",s(this.Jb,this));U.call(this);Ya("_cbq",s(this.hb,this))}ba(Y,U);
Y.prototype.q=function(){Y.S.q.call(this);var a=this.ka;S().u=a;a=this.La;S().t=a;this.za=i;Za(this.a);a=n.location;M(this.a,"pingServer","ping.chartbeat.net");M(this.a,"title",document.title);M(this.a,"domain",a.hostname);this.a.path=this.a.path?Q(this.a.path):cb(!!this.a.useCanonical);this.ga=na(a.hostname);this.a.domain=na(this.a.domain);this.tb=D(F,"c",this.Pb,this);this.ub=D(F,"r",this.Qb,this);this.Y=i};Y.prototype.qb=function(a){this.za=a};
Y.prototype.qa=function(){this.D.update("_chartbeat4",["t="+this.La,"E="+this.F.N,"EE="+this.U.N,"x="+mb(this),"c="+Math.round((r()-this.ba)/600)/100,"y="+C("Height"),"w="+za("Height")].join("&"),60,g,g,1)};var Va="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE,sv".split(",");m=Y.prototype;
m.ja=function(a){this.gb++;var b={};b.g=this.a.uid;b.g0=N(this.a,"sections");b.g1=N(this.a,"authors");b.g2=N(this.a,"zone");b.g3=N(this.a,"sponsorName");b.g4=N(this.a,"type");!this.a.noCookies&&this.D.isSupported()?b.n=this.Nb:b.nc=1;b.c=Math.round((r()-this.ba)/600)/100;b.E=this.F.N;b.EE=this.U.N;var c=mb(this);this.ha=Math.max(this.ha,c);b.x=c;b.m=this.ha;b.y=C("Height");b.o=C("Width");b.w=za("Height");b.b=this.Ja?this.Ja:"";if(this.Ya)b.f=this.Ya;b[""]=$a(this.a);b.t=this.La;b.V=86;b.tz=(new Date).getTimezoneOffset();
b.sn=this.gb;b.sv=this.Tb;c=this.F.Z;b.h=encodeURIComponent(this.a.domain);b.p=encodeURIComponent(this.a.path);b.u=this.ka;b.d=encodeURIComponent(this.ga);b.j=Math.round((this.$+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.ba;b.eD=G.ea("mousedown",d);b.eM=G.ea("mousemove",d);b.eK=G.ea("keydown",d);b.eR=G.ea("resize",d);b.eS=G.ea("scroll",d);G.Rb();G.sb()?b.W=1:this.a.reading&&+this.a.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=nb(this);if(this.Ka){this.Ka=l;if(c)this.Y=Pb(this);b.i=pb(this);d=
this.a.hudTrackable;d!==g&&(b.L=d?"1":"0");this.a.alias&&(b.PA=encodeURIComponent(this.a.alias))}if(c){if(this.Y){if(b.v=encodeURIComponent(this.Y.path),b.K=Qb(this.Y),this.Y.Ga>1)b.l1=this.Y.Ga}else b.v=ob(this);this.a.virtualReferrer&&(b.vp=1)}else b.r=ob(this);c=xa(b.v);S().v=c;c=xa(b.r);S().r=c;b.A=this.za?this.za:"";b._c=Sa("utm_campaign",this.a.campaignTag);b._m=Sa("utm_medium",this.a.mediumTag);this.a.idSync?(c=[],ea(new ca,this.a.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=
qb(this);b.C=this.a.mobileApp?1:"";b.KK=a?Qb(a):"";a=this.D;c=a.Qa;a.Qa=l;b.l=c?1:"";this.F.Z=0;this.sa(qa()+"//"+this.a.pingServer+"/ping?"+Ua(b))};
m.Jb=function(a){var b=this.a,c=b.playerdomain||this.ga;if(a.origin.replace(/^https?:\/\//,"")===c.replace(/^https?:\/\//,""))if(c=a.data,A(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.hb(a));else if(c=="cbdata?"){var c="&u="+R("u"),d="&t="+R("t"),e="&v="+R("v"),f="&r="+R("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+pb(this)+"&referrer="+ob(this)+"&internal="+(nb(this)?
"1":"0")+"&subdomain="+encodeURIComponent(this.ga)+c+d+e+f+"&utoken="+this.ka;a.source.postMessage(b,"*")}};m.hb=function(a){a[0]==="_demo"&&this.a._demo?this.a._demo=this.a._demo+"%2C"+a[1]:this.a[a[0]]=a[1];this.$=0};function Rb(a){a=a.replace(/-{2,}/g,"-");a=Wa(a);a.pathname=Q(a.pathname);return a}m.Pb=function(a){Sb(this,a,"c")};m.Qb=function(a){Sb(this,a,"r")};
function Sb(a,b,c){if(a.Ma&&r()-a.ba>=a.Fa)a.terminate();else{var d=b.href||"",d=Rb(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==n.location.hostname,d=Xa(d),f=Aa(b,function(a){return a.id}),o=Cb(b,f),k;f?(o&&(o="/"+o),o="*[@id='"+f.id+"']"+o,k=Cb(b)):k=o;f=p(o);k=p(k);b=sb(b,g,h);c={left:b.x,top:b.y,path:a.a.path,href:d,Ua:f,ya:k,Ta:o,Oa:c,Ga:0,Db:a.a.domain};a.ja(c);e||a.D.update("_chartbeat5",Tb(c),60,l,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Qb(a){return[a.left,a.top,a.Ua,encodeURIComponent(a.Ta),a.Oa,encodeURIComponent(a.href),a.ya].join("::")}function Tb(a){var b=encodeURIComponent(a.Ta),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Ua,b,a.Oa,a.ya,encodeURIComponent(a.Db)].join(",")}
function Pb(a){var b=a.D.k("_chartbeat5");if(!b)return i;var c=a.a.domain,d=b.split("::"),b=d.length,e,f=i,o,k=Rb(n.location.href),j=Xa(k);q(d,function(a,b){var d=a.split(","),k=d.length>8?decodeURIComponent(d[8]):l;if(k&&k!==c)return h;k=sa(j,decodeURIComponent(d[3]));if(k===0)return e=d,f=b,l;if(o===g||k<o)o=k,e=d,f=b});if(f===i)return i;d.splice(f,1);a.D.create("_chartbeat5",d.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),
href:decodeURIComponent(e[3]),Ua:e[4]||"",Ta:a,ya:e.length>7?e[7]:"",Oa:e.length>6?e[6]:"c",Ga:b}}m.terminate=function(){E(F,this.tb);E(F,this.ub);Y.S.terminate.call(this)};if(!n.pSUPERFLY){var Ub=new Y,Z={};n.pSUPERFLY=Z;var Vb=n.pSUPERFLY_mab,$=n.pSUPERFLY_pub,Wb=[];Vb&&Wb.push(Vb);if($)Wb.push($),$.addEngagedAdFilter&&(Z.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Z.refreshAd=$.refreshAd),$.registerGptSlot&&(Z.registerGptSlot=$.registerGptSlot),Ya("_cba",function(a){a()});Z.virtualPage=function(a,b){if(!I){var c=n._sf_async_config;c.virtualReferrer=qa()+"//"+c.domain+c.path;c.path=Q(a);b&&(c.title=b);Ub.la();q(Wb,function(a){a.evps()});Ub.kb();q(Wb,function(a){a.svps()})}};
Z.activity=s(Ub.qb,Ub);kb(Ub);var Xb=P.B(h);if(Xb)if(Xb.getItem("_cb_ip")){var Yb=n.location;(!/^(.+[.])?chartbeat\.com$/.test(Yb.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Yb.pathname))||Nb()}else v(n,"message",Ob)};})();
