(function(){var j=null,k=false,m=this;function q(a){var b="",a=s(encodeURIComponent(a));a.splice(5,a.length);w(a,function(a){if(a==0)a="A";else{a>>>=0;for(var d="",e;a>0;)e=a%64,d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+d,a>>>=6;a=d}b+=a});return b}
function s(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,p=3285377520,l=[],h,n,o,u,r,v=Math.ceil((a.length/4+2)/16),t=[v],i=0,g;i<v;i++){t[i]=[];for(h=0;h<16;h++)t[i][h]=a.charCodeAt(i*64+h*4)<<24|a.charCodeAt(i*64+h*4+1)<<16|a.charCodeAt(i*64+h*4+2)<<8|a.charCodeAt(i*64+h*4+3)}i=(a.length-1)*8;a=v-1;t[a][14]=Math.floor(i/Math.pow(2,32));t[a][15]=i&4294967295;for(i=0;i<v;i++){for(g=0;g<16;g++)l[g]=t[i][g];
for(g=16;g<80;g++)l[g]=(l[g-3]^l[g-8]^l[g-14]^l[g-16])<<1|(l[g-3]^l[g-8]^l[g-14]^l[g-16])>>>31;a=c;h=d;n=e;o=f;u=p;for(g=0;g<80;g++)r=Math.floor(g/20),r=(a<<5|a>>>27)+(r==0?h&n^~h&o:r==1?h^n^o:r==2?h&n^h&o^n&o:h^n^o)+u+b[r]+l[g]&4294967295,u=o,o=n,n=h<<30|h>>>2,h=a,a=r;c=c+a&4294967295;d=d+h&4294967295;e=e+n&4294967295;f=f+o&4294967295;p=p+u&4294967295}return[c,d,e,f,p]}
function x(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}function y(a){return typeof a!=="undefined"}function w(a,b){if((!!a&&a.constructor===Object)===true)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===k)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===k)break}}
function z(a){if((!!a&&a.constructor===Object)===k)return"";var b=[];w(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}var A=m.setInterval,B=m.clearInterval,C=m.setTimeout,D=m.clearTimeout;function E(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),w(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b};var F="adIdentifier";function G(a,b){var c=j;b&&(c=b.getAttribute(a));if(c===j){var d;var e,f;f="*";e=b||document;if("querySelectorAll"in e)d=e.querySelectorAll(f+"["+a+"]");else{d=[];e=e.getElementsByTagName(f);for(f=e.length;f--;)e[f].getAttribute(a)&&d.push(e[f])}d.length!==0&&(c=d[0].getAttribute(a))}return c}function H(a,b,c){c=c||"";if(a===void 0)a=k;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?k:H(a.parentNode,b,c)}return a};function I(a){J().c=a}function K(){var a={},b=J();return y(a)&&!y(b.c)?a:b.c}function J(){y(m._cb_shared)||(m._cb_shared={});return m._cb_shared};function L(){this.q=m._sf_async_config||{};this.l=this.q[F]||"data-cb-ad-id";this.i=window.location!==window.parent.location;this.h=M;this.b=(this.a=N(this))?this.a.getAttribute(this.l)||this.a.id||"":"";this.n=G("data-cb-account-id",this.a)||"";this.r=G("data-cb-domain",this.a)||"";var a={cbType:"campaignMessage"};a.campaignId=G("data-cb-campaign-id",this.a)||"";a.creativeId=G("data-cb-creative-id",this.a)||"";a.placementId=G("data-cb-placement-id",this.a)||"";a.siteId=G("data-cb-site-id",this.a)||
"";a.server_height=G("data-cb-creative-height",this.a)||"";a.server_width=G("data-cb-creative-width",this.a)||"";a.engagedSeconds=G("data-cb-engaged-seconds",this.a)||"";a.exclude=G("data-cb-exclude",this.a)||"";a.lineId=G("data-cb-line-id",this.a)||"";a.noRefresh=G("data-cb-no-refresh",this.a)||"";a.roadblock=G("data-cb-roadblock",this.a)||"";a.vizu=z(O());this.o=a;this.k=z(this.o);for(var a="",b=0;b<16;b++)a+=Math.random();this.p=q(a+this.k);this.d=x(this.d,this);a=x(this.g,this);this.f=C(a,2E4);
if(this.i===k)P(this);else if("postMessage"in window===true){this.j=j;var c=this.d,a=window;a.addEventListener?a.addEventListener("message",c,k):a.attachEvent&&a.attachEvent("onmessage",c);c=x(this.m,this);this.j=A(c,100);this.m()}else{D(this.f);this.f=j;a="/cmploader.html";if(b=document.getElementById("campaign_tracker")){var d=b.src,b="";if(d){var b=document.createElement("a"),e=m.location;if(!/^https?:/.test(d)&&d.indexOf("javascript:")!==0)if(d.indexOf("//")===0)d=e.protocol+d;else if(d.indexOf("/")===
0){var f;f=e.protocol;var p=e.port;f=p?f==="http:"&&p==="80"||f==="https:"&&p==="443":true;f=f?"":e.port;d=e.protocol+"//"+e.hostname+(f?":"+f:"")+d}else{e=document.baseURI||e.href;f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);d=f===-1?"/"+d:e.substr(0,f)+"/"+d}b.href=d;b=b.search}b=E(b);b.loaderpath&&(a=b.loaderpath);b.loaderhost&&(c=b.loaderhost)}c&&(c="//"+c,c+=a.charAt(0)!=="/"?"/"+a:a,c.indexOf("?")===-1&&(c+="?"),a=["ct="+this.p,"pm=0","if="+(this.i?
1:0),"cf="+this.h,"g="+this.n,"d="+this.r].join("&"),b=document.createElement("iframe"),b.setAttribute("src",c+"campaigndata="+encodeURIComponent(this.k)+"&campaignping="+encodeURIComponent(a)),document.body.appendChild(b))}}var M=0;L.prototype.m=function(){"postMessage"in window===true&&window.top.postMessage(this.k,"*")};
L.prototype.g=function(){var a=this.d,b=window;b.removeEventListener?b.removeEventListener("message",a,k):b.detachEvent&&b.detachEvent("onmessage",a);B(this.j);this.j=j;D(this.f);this.f=j};L.prototype.d=function(a){a=a.data;typeof a==="string"&&a.indexOf("cbdata::ack")===0&&this.g()};
function O(){var a=document.getElementsByTagName("script"),b={};if(!G("data-cb-vizu"))return b;var c=/^(?:https?:)?\/\/[^.\s]+\.vizu\.com\/cdn\/(\d+)\/(\d+)\/(\d+)\/(\d+)\/[^?]*\?(.*)/;w(a,function(a){if((a=a.getAttribute("src"))&&a.indexOf("vizu.com")>=0)if((a=c.exec(a))&&a.length===6)return b=E(a[5]),b.vzcid=parseInt(a.slice(1,5).join(""),10),k});return b}
function N(a){var b=j;if(!a.i){var c=m.document.currentScript;a.h=1;if(!c)a.h=2,w(m.document.getElementsByTagName("script"),function(a){if(typeof a.src==="string"&&a.src.indexOf("//static.chartbeat.com/js/campaign_tracker.js")!=-1&&a.getAttribute("data-cb-campaign-associated")!="1")return c=a,c.setAttribute("data-cb-campaign-associated",1),k});c&&(a=H(c,a.l))&&(b=a)}return b}
function P(a){if(a.b){var b=K();b[a.b]=b[a.b]||[];var c={};c.e=a.a;c.c=x(function(){this.g()},a);b[a.b].push(c);I(b)}else a.g();window.pSUPERFLY_pub&&window.pSUPERFLY_pub.updateCampaignData&&window.pSUPERFLY_pub.updateCampaignData()};new L;})();
