(function() { //Sonobi - Morpheus version:3.5.4
'use strict';var y="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,A={};function B(e,n){(A[e]=A[e]||[]).push(n);var m=y;e=e.split(".");for(var k=0;k<e.length-1&&m;k++)m=m[e[k]];e=e[e.length-1];m&&m[e]instanceof Function&&(m[e]=n(m[e]))}
function E(){E=function(){};if(!y.Symbol){y.Symbol=fa;var e=[],n=function(n){return function(k){e=[];k=n(k);for(var p=[],q=0,v=k.length;q<v;q++){var w;a:if(w=k[q],14>w.length)w=!1;else{for(var z=0;14>z;z++)if(w[z]!="jscomp_symbol_"[z]){w=!1;break a}w=!0}w?e.push(k[q]):p.push(k[q])}return p}};B("Object.keys",n);B("Object.getOwnPropertyNames",n);B("Object.getOwnPropertySymbols",function(m){return function(k){n.a=Object.getOwnPropertyNames(k);e.push.apply(m(k));return e}})}}var ga=0;
function fa(e){return"jscomp_symbol_"+e+ga++}function M(){E();y.Symbol.iterator||(y.Symbol.iterator=y.Symbol("iterator"));M=function(){}}function N(e){M();E();M();var n=e[Symbol.iterator];if(n)return n.call(e);var m=0;return{next:function(){return m<e.length?{done:!1,value:e[m++]}:{done:!0}}}}
function ha(e,n){function m(){}m.prototype=n.prototype;e.prototype=new m;e.prototype.constructor=e;for(var k in n)if(Object.defineProperties){var p=Object.getOwnPropertyDescriptor(n,k);p&&Object.defineProperty(e,k,p)}else e[k]=n[k]}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(e,n,m){if(m.get||m.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[n]=m.value)};
function O(e,n){if(n){for(var m=y,k=e.split("."),p=0;p<k.length-1;p++){var q=k[p];q in m||(m[q]={});m=m[q]}k=k[k.length-1];p=m[k];n=n(p);if(n!=p){e=A[e]||[];for(p=0;p<e.length;p++)n=e[p](n);ia(m,k,{configurable:!0,writable:!0,value:n})}}}O("Object.assign",function(e){return e?e:function(e,m){for(var k=1;k<arguments.length;k++){var p=arguments[k];if(p)for(var q in p)Object.prototype.hasOwnProperty.call(p,q)&&(e[q]=p[q])}return e}});
function ja(e,n){M();e instanceof String&&(e+="");var m=0,k={next:function(){if(m<e.length){var p=m++;return{value:n(p,e[p]),done:!1}}k.next=function(){return{done:!0,value:void 0}};return k.next()}};k[Symbol.iterator]=function(){return k};return k}O("Array.prototype.keys",function(e){return e?e:function(){return ja(this,function(e){return e})}});O("Number.EPSILON",function(){return Math.pow(2,-52)});O("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});O("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});
O("Array.from",function(e){return e?e:function(e,m,k){M();m=m?m:function(e){return e};var p=[],q=e[Symbol.iterator];if("function"==typeof q)for(e=q.call(e);!(q=e.next()).done;)p.push(m.call(k,q.value));else for(var q=e.length,v=0;v<q;v++)p.push(m.call(k,e[v]));return p}});O("Array.prototype.find",function(e){return e?e:function(e,m){a:{var k=this;k instanceof String&&(k=String(k));for(var p=k.length,q=0;q<p;q++){var v=k[q];if(e.call(m,v,q,k)){e=v;break a}}e=void 0}return e}});
(function(e){function n(a){this.a(a);this.gb=new m(a);this.J=new I(a)}function m(a){this.a=a.analyticsSettings;this.J=new I(a)}function k(a,b){this.c=a;this.g=b;this.caller=new F;this.a=[]}function p(a,b){this.c=a;this.a={};this.aa=b}function q(a,b,c,d,f,J,l){this.ca=r.ya();this.w=d;this.O=f;this.V=0;this.P=c;this.da=b;this.a="";this.C=a;this.h={};this.ra="";this.b=10;this.T=this.i=0;this.W=1;this.m=[];this.g={};this.U=l;this.F=this.S=0;"function"===typeof J.ea&&J.ea(this.wa(1))}function v(a){this.name=
a.name;this.ta=a.ta;this.Ga=a.Ga;this.request=a.request;this.parse=a.parse;this.done=Function;this.caller=new F;this.X={};this.c={};this.b=Promise.resolve({});this.a=!1}function w(a,b){if(!b)throw Error("Provide an adapter name in your AdapterSettingsConfigInterface constructor.");this.g=a.adapterSettings;this.a=new z(a);a=this.g;for(var c={},d=0;d<a.length;d++)c[a[d].name]=a[d];this.b=c;this.u=b}function z(a){this.a=a.platformSettings;this.J=new I(a)}function I(a){this.a=a.globalSettings}function D(a,
b,c,d){this.c=a;this.a={};this.g=c;this.aa=d;var f=this;this.xa=function(a){if("object"!==typeof a)return f.a;a.Z=!1;return Object.keys(f.a).reduce(function(b,c){var d=f.a[c],e;for(e in a)if(d[e]!==a[e])return b;b[c]=d;return b},{})};this.ga=function(a){if("object"===typeof a)return a.Z=!1,f.a[Object.keys(f.a).find(function(b){b=f.a[b];for(var c in a)if(b[c]!==a[c])return!1;return!0})]};this.i=function(){};this.b=new t(this.c,this);g.sbi_km.API.render=function(a,b,c,d){var e=Date.now();if(b=f.a[b])b.Ea[b.ba.id]=
e,f.b.$a(b,a,b.ba.creative,b.ba.size,c,d).then(function(a){a=Object.keys(a.Ea);a=f.g.sa[a[0]];f.c.log("sbi",200019,[a.f,a.A]);a.response=6;a.la=!0;f.aa.ea(a.wa(3))},function(a){a=Object.keys(a.Ea);a=f.g.sa[a[0]];f.c.log("sbi",200021,[a.f,a.A])}),b.ba={}};this.b.L("initialized",function(a,b){f.c.log("sbi",200003,[a]);f.h(a);"function"===typeof b&&b();f.b.o("slotsDefined",function(a){f.c.log("sbi",200027,[a]);f.h(a)})});this.b.o("slotsDestroyed",function(a){a.forEach(function(a){var b=f.b.F(a);a=f.b.Ja(a);
for(var c in f.a)f.a[c].l==b&&f.a[c].j==a&&(f.a[c].Z=!0,f.c.log("sbi",200028,[f.a[c]]))},this)});this.b.o("getSlots",function(a,b){"object"!==typeof a?b(f.a):(a.Z=!1,b(Object.keys(f.a).reduce(function(b,c){var d=f.a[c],e;for(e in a)if(d[e]!==a[e])return b;b[c]=d;return b},{})))});this.b.o("findSlot",function(a,b){"object"!==typeof a?b({}):(a.Z=!1,b(f.a[Object.keys(f.a).find(function(b){b=f.a[b];for(var c in a)if(b[c]!==a[c])return!1;return!0})]))});this.b.o("slotsRequestingRender",function(a){var b=
f.m(a.B);f.i(b,a.done)});this.b.o("newPageViewRequested",function(){f.b.cb()});this.b.o("log",function(a){f.c.log.apply(f.c,Array.isArray(a)?a:[a])})}function t(a,b){this.b={};var c=this;this.g=!1;this.na=this.pa=Function;this.Ka={};this.a={};this.c=a;this.$=[];this.xa=b.xa;this.ga=b.ga;g.googletag=g.googletag||{};g.googletag.cmd=g.googletag.cmd||[];g.googletag.cmd[null!=g.googletag.cmd.length?"unshift":"push"](function(){c.Ka=g.googletag;c.a=c.Ka.pubads();c.a.disableInitialLoad();c.Za();c.bb()});
this.m={xb:!1,Na:!1,Oa:!1,jb:!1};this.ja={}}function L(){this.b={}}function G(a){this.caller=new F;this.g=a;this.a=!1;this.navigationStart=g.performance.timing.navigationStart}function F(){}function ka(a){return parseInt(a,10)}function S(a,b){var c;if(b){if(-1!==b.indexOf(".")){b=b.split(".");for(var d=!1,f=0;f<b.length;f++){if("object"!==typeof a){d=!0;break}a=S(a,b[f])}d||(c=a);return c}d="get"+b[0].toUpperCase()+b.slice(1);b=a&&"function"===typeof a[d]?d:b;a&&(a.hasOwnProperty(b)||"function"===
typeof a[b])&&(c="function"===typeof a[b]?a[b]():a[b]);return c}}function T(a){return a?'<script type="text/javascript" src="'+a+'">\x3c/script>':""}function U(a,b){if(!a)return"";b=b.split("x");return'<iframe id="'+C()+'" width="'+b[0]+'" height="'+b[1]+'" marginwidth="0" marginheight="0" style="border:0" frameborder="0" src="'+a+'" border="0" scrolling="no" vspace="0" hspace="0"></iframe>'}function V(a){return a?'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+
a+'"></div>'):""}function W(a,b){var c=[];a.forEach(function(a){-1!==b.indexOf(a)&&c.push(a)});return c}function X(){return[g.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,g.innerHeight||document.documentElement.clientHeight||document.body.clientHeight]}function Y(a,b){for(var c=0;c<b.length;c++){var d="lt"in b[c]&&a<b[c].lt||!("lt"in b[c]);"ge"in b[c]&&a>=b[c].ge&&d&&("set"in b[c]?a=b[c].set:"round"in b[c]&&(a=Math.round(a*b[c].round)/b[c].round))}return a}function Z(){return"Worker"in
g&&"Blob"in g}function aa(a,b,c){Object.keys(b).forEach(function(d){a=a.replace(c+d+c,b[d])});return a}function C(){return la()+Math.random().toString(16).substr(2)}var g=window;(function(){(function(a){0=="performance"in a&&(a.performance={});Date.now=Date.now||function(){return(new Date).getTime()};if(0=="now"in a.performance){var b=Date.now();a.performance.timing&&a.performance.timing.navigationStart?b=a.performance.timing.navigationStart:a.performance.timing={navigationStart:Date.now()};a.performance.now=
function(){return Date.now()-b}}})(g);Object.assign||Object.defineProperty(Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:function(a,b){if(void 0===a||null===a)throw new TypeError("Cannot convert first argument to object");for(var c=Object(a),d=1;d<arguments.length;d++){var f=arguments[d];if(void 0!==f&&null!==f)for(var e=Object.keys(Object(f)),l=0,h=e.length;l<h;l++){var u=e[l],g=Object.getOwnPropertyDescriptor(f,u);g&&g.enumerable&&(c[u]=f[u])}}return c}});g.Promise||(g.Promise=
function(){function a(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)}function b(){}function c(a,b){return function(){a.apply(b,arguments)}}function d(a){if("object"!==typeof this)throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.D=0;this.La=!1;this.G=void 0;this.R=[];g(a,this)}function f(a,b){for(;3===a.D;)a=a.G;0===a.D?a.R.push(b):(a.La=!0,x(function(){var c=1===a.D?b.rb:
b.sb;if(null===c)(1===a.D?e:l)(b.M,a.G);else{var d;try{d=c(a.G)}catch(f){l(b.M,f);return}e(b.M,d)}}))}function e(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var d=b.then;if(b instanceof Promise){a.D=3;a.G=b;h(a);return}if("function"===typeof d){g(c(d,b),a);return}}a.D=1;a.G=b;h(a)}catch(f){l(a,f)}}function l(a,b){a.D=2;a.G=b;h(a)}function h(b){2===b.D&&0===b.R.length&&x(function(){b.La||a(b.G)});for(var c=0,
d=b.R.length;c<d;c++)f(b,b.R[c]);b.R=null}function u(a,b,c){this.rb="function"===typeof a?a:null;this.sb="function"===typeof b?b:null;this.M=c}function g(a,b){var c=!1;try{a(function(a){c||(c=!0,e(b,a))},function(a){c||(c=!0,l(b,a))})}catch(d){c||(c=!0,l(b,d))}}var k=setTimeout,x="function"===typeof setImmediate&&setImmediate||function(a){k(a,0)};d.prototype["catch"]=function(a){return this.then(null,a)};d.prototype.then=function(a,c){var d=new this.constructor(b);f(this,new u(a,c,d));return d};d.all=
function(a){var b=Array.prototype.slice.call(a);return new d(function(a,c){function d(e,u){try{if(u&&("object"===typeof u||"function"===typeof u)){var h=u.then;if("function"===typeof h){h.call(u,function(a){d(e,a)},c);return}}b[e]=u;--f||a(b)}catch(J){c(J)}}if(!b.length)return a([]);for(var f=b.length,e=0;e<b.length;e++)d(e,b[e])})};d.resolve=function(a){return a&&"object"===typeof a&&a.constructor===d?a:new d(function(b){b(a)})};d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
c){for(var d=0,f=a.length;d<f;d++)a[d].then(b,c)})};d._setImmediateFn=function(a){x=a};d._setUnhandledRejectionFn=function(b){a=b};return d}())})();var la=function(){var a=0;return function(){a++;return a}}(),ba={highestCPMWins:function(a,b){if(0==a.length)return null;for(var c={f:0},d=0;d<a.length;d++)c.f>=a[d].f?b.log("sbi",200017,[a[d].f,a[d].A]):c=a[d];return c.f?c:null},sonobiDealWinsOverHighestCPM:function(a,b){if(0==a.length)return null;for(var c={f:0},d=0;d<a.length;d++){if("sonobi"==a[d].A&&
a[d].I){c=a[d];a.forEach(function(f){f!==c&&b.log("sbi",200017,[a[d].f,a[d].A])});break}c.f>=a[d].f?b.log("sbi",200017,[a[d].f,a[d].A]):c=a[d]}return c.f||c.I?c:null},lowestDealPriorityWinsOverHighestCPM:function(a,b){if(0==a.length)return null;a.sort(function(a,b){return a.Y-b.Y});var c=a[0].Y,d=a.filter(function(a){return a.Y===c});a={f:0};for(var d=N(d),f=d.next();!f.done;f=d.next())f=f.value,a.f>=f.f?b.log("sbi",200017,[f.f,f.A]):a=f;return a.f||a.I?a:null}},r={ya:C,m:function(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;
return b.test(a)?a.replace(b,function(a){var b={"\b":"\\b"," ":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"}[a];return("string"==typeof b?b:"\\u")+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}):a},ja:function(a){if(a){var b;try{b=a.contentWindow?a.contentWindow.document:a.contentDocument.document?a.contentDocument.document:a.contentDocument}catch(c){return}return b}},$:function(){var a=document.createElement("iframe");a.id=C();a.height=0;a.width=0;a.hspace="0";a.vspace="0";a.marginWidth=
"0";a.marginHeight="0";a.style.border="0";a.frameBorder="0";a.border="0px";a.scrolling="no";a.src="about:blank";a.style.display="none";return a},qa:aa,Ha:Z,pa:function(a,b){for(var c=0,d=a.length>b.length?b.length:a.length,f=a.length<b.length?b.length:a.length,e=0;e<d;e++)a[e]==b[e]&&c++;return c/f},a:ba,b:Y,na:X,w:W,F:function(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]="+a}).join("&"):b+"="+a[b]}).join("&")},mb:function(a){try{var b=new RegExp(a,
"i"),c=g.performance.getEntriesByType("resource").filter(function(a){return b.test(a.name)});return c.length&&c[0]?c[0].duration:null}catch(d){return null}},Ca:function(a){return void 0!=={sizes:1,Ab:1,timeout:1}[a]},Qa:function(a){var b=g.innerWidth,c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c].viewport.lt||Number.MAX_SAFE_INTEGER;if(b>=(a[c].viewport.ge||0)&&b<d)return c}},ob:function(a,b){return a.reduce(function(a,d){(a[d[b]]=a[d[b]]||[]).push(d);return a},{})},i:V,g:U,h:T,ib:function(a,b,c){switch(void 0===
b?"SCRIPT":b){case "SCRIPT":return T(a);case "IFRAME":return U(a,void 0===c?"1x1":c);case "TRACK":return V(a);case "SCRIPT_BLOCK":return a?'<script type="text/javascript">'+a+"\x3c/script>":""}return""},Aa:S,ua:function(a){var b=/^\d{1,4}x\d{1,4}$/;return"string"===typeof a&&b.test(a)?a.split("x").map(ka):a}};F.prototype.qb=function(a){var b,c;null==b&&(b="sbi_"+C());null==c&&(c=!1);a=a.replace("%%callback%%",b);c=c&&Z();var d=this;return new Promise(function(f){function e(a){f(a)}if(c){var l=URL.createObjectURL(new Blob(["(function(){\n\t\t\t\t\t\tself."+
b+" = function(data){\n\t\t\t\t\t\t\tself.postMessage(JSON.stringify(data));\n\t\t\t\t\t\t};\n\t\t\t\t\t\tself.addEventListener('message', function(e) {\n\t\t\t\t\t\t\timportScripts(e.data);\n\t\t\t\t\t\t})\n\t\t\t\t\t})()"],{type:"application/javascript"})),h=new Worker(l);h.addEventListener("message",function(a){f(JSON.parse(a.data))},!1);h.postMessage(a);URL.revokeObjectURL(l)}else g[b]=e,d.a(a)})};F.prototype.a=function(a){var b;b=void 0===b?"":b;return new Promise(function(c,d){var f=document.createElement("script");
f.src=a;f.id=b;f.async=!0;document.head.appendChild(f);f.addEventListener?f.addEventListener("load",function(){c()}):f.readyState?f.onreadystatechange=function(){3==f.readyState&&c()}:d()})};var P=[];G.prototype.log=function(a,b,c,d){d=null!=d?d-this.navigationStart:0+g.performance.now();a={dateTime:d,time:d-0,id:b,service:a};a.Va=c||[];P.push(a);this.a&&"logData"in g.sbi_km&&(c=g.sbi_km.logData,this.b(c[a.id].service,a.time,c[a.id].template,a.Va))};G.prototype.i=function(){P.sort(function(a,b){return a.time-
b.time});return P};G.prototype.b=function(a,b,c,d){var f=[a,b];a=c.apply(c,d);Array.isArray(a)?a.forEach(function(a){return f.push(a)}):f.push(a);g.console.log.apply(console,f)};G.prototype.h=function(){var a=this;this.a=!0;this.caller.a(this.g.url+"/morpheus_console.js").then(function(){var b=g.sbi_km.logData;a.i().forEach(function(c){a.b(b[c.id].service,c.time,b[c.id].template,c.Va)})})};L.prototype.h=function(a){if(a in this.b){var b=Array.from(arguments);b.shift();this.b[a].o.forEach(function(a){return a.apply(a,
b)});this.b[a].L.forEach(function(a){return a.apply(a,b)});this.b[a].L=[]}};L.prototype.L=function(a,b){this.b[a]=this.b[a]||{o:[],L:[]};this.b[a].L.push(b)};L.prototype.o=function(a,b){this.b[a]=this.b[a]||{o:[],L:[]};this.b[a].o.push(b)};ha(t,L);t.prototype.$a=function(a,b,c,d,f,e){var l=this,h=this,u=a.l;return new Promise(function(k,K){var x=a;h.c.log("sbi",200032,[x]);a=l.i(a.l);a.rendering=!0;f&&Object.keys(f).forEach(function(a){Array.isArray(f[a])||(f[a]=[f[a]]);c=c.replace("%%"+a+"%%",f[a].join(","))});
d=d.split("x");d={N:parseInt(d[0],10),K:parseInt(d[1],10)};if(l.Xa(a,d.N,d.K))if(e)K=g.document.getElementById(u).getElementsByTagName("div")[0].childNodes[0],K.width=d.N,K.height=d.K,b.postMessage({creative:c,message:"SBI_RENDER"},"*");else{if(b.inDapIF)try{g.document.getElementsByName(b.name)[0].width=d.N,g.document.getElementsByName(b.name)[0].height=d.K}catch(m){h.c.log("sbi",200012)}b.document.write(c)}else K(x);h.c.log("sbi",200033,[x]);k(x)})};t.prototype.Ha=function(a){var b=a.getTargetingMap(),
c=Object.keys(b),d=c.filter(function(a){return"sbi"!==a.substr(0,3)});if(c.length!==d.length)for(a.clearTargeting(),c=N(d),d=c.next();!d.done;d=c.next())d=d.value,a.setTargeting(d,b[d])};t.prototype.i=function(a){var b=this;return this.w().find(function(c){return b.F(c)==a})||null};t.prototype.F=function(a){return a&&"getSlotElementId"in a?a.getSlotElementId():null};t.prototype.w=function(){return this.a.getSlots()};t.prototype.Ja=function(a){return a.getAdUnitPath()};t.prototype.Xa=function(a,b,
c){var d=!1;this.ia(a).forEach(function(a){d=d||a.N==b&&a.K==c});return d};t.prototype.qa=function(a){return this.ia(a).map(function(a){return a.N+"x"+a.K})};t.prototype.ia=function(a){a=a.getSizes.apply(a,X());a=null!=a?a:[];return a.filter(function(a){return"function"===typeof a.getWidth}).map(function(a){return{N:a.getWidth(),K:a.getHeight()}})};t.prototype.ab=function(a,b){a=this.i(a);if(null!=a)for(var c in b)a.setTargeting(c,b[c])};t.prototype.bb=function(){var a=this,b=g.googletag.debug_log.log;
g.googletag.debug_log.log=function(){var c=b.apply(g.googletag.debug_log,arguments);a.h("log",["dfp",c.getMessage().getMessageId()+1E5,c.getMessage().getMessageArgs(),c.getTimestamp().getTime()])}.bind(g.googletag.debug_log)};t.prototype.cb=function(){this.a.updateCorrelator()};t.prototype.Za=function(){var a=this,b=g.googletag.defineSlot;g.googletag.defineSlot=g.googletag.defineUnit=function(){"/"!=arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var c=b.apply(this,arguments),d=c.defineSizeMapping;
c.defineSizeMapping=function(a){d.call(this,a);return this};var f=c.getAdUnitPath;c.getAdUnitPath=function(a){a=f.call(this,a);return("/"!=a.charAt(0)?"/":"")+a};a.g&&a.h("slotsDefined",[c]);return c};var c=g.googletag.defineOutOfPageSlot;g.googletag.defineOutOfPageSlot=function(){"/"!=arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var b=c.apply(this,arguments),d=b.defineSizeMapping;b.defineSizeMapping=function(a){d.call(this,a);return this};var f=b.getAdUnitPath;b.getAdUnitPath=function(a){a=
f.call(this,a);return("/"!=a.charAt(0)?"/":"")+a};b.isOutOfPage=!0;a.g&&a.h("slotsDefined",[b]);return b};var d=g.googletag.destroySlots;g.googletag.destroySlots=function(){var b=arguments.length?arguments[0]:a.a.getSlots();a.h("slotsDestroyed",b);return d.apply(this,arguments)};this.na=this.a.refresh;this.a.refresh=function(){var b=Array.from(arguments),c={};0<b.length&&Array.isArray(b[0])?0==b[0].length?c.B=a.w():(c.B=[],b[0].forEach(function(b){b&&"object"===typeof b&&"function"===typeof b.getSizes?
c.B.push(b):a.c.log("sbi",200036,[b])})):c.B=a.w();c.done=function(){a.c.log("sbi",200029,[c.B]);a.na.apply(a.a,b)};c.B.forEach(function(b){a.Ha(b)});a.h("slotsRequestingRender",c)};this.pa=g.googletag.display;g.googletag.display=function(){if(a.g){var b=Array.from(arguments);a.pa.apply(g.googletag,b);if(!a.m.Na)if(a.m.Oa){if((b=a.ga({l:b[0]}))&&!b.fa){var c=a.xa({fa:!1}),d=C();a.ja[d]={};if(0<Object.keys(c).length){Object.keys(c).forEach(function(a){c[a].fa=!0});a.ja[d]=c;var b=Object.keys(c).map(function(b){return a.i(c[b].l)}),
f={};f.B=b;f.done=function(){var b=a.ja[d],c=Object.keys(b).map(function(c){return a.i(b[c].l)});a.c.log("sbi",200029,[f.B]);a.na.apply(a.a,[c])};f.B.forEach(function(b){a.Ha(b)});a.h("slotsRequestingRender",f)}}}else if(0<b.length){var e=a.ga({l:b[0]});e&&(e.fa=!0);if(b=a.i(b[0]))a.c.log("sbi",200030,[b]),a.a.refresh([b],{changeCorrelator:!1})}}else a.c.log("sbi",200035,[arguments[0]]),a.$.push(arguments[0])};var f=this.a.addEventListener;this.a.addEventListener=function(){var b=Array.from(arguments),
c=b[1];"slotRenderEnded"==b[0]&&(b[1]=function(){var a=Array.from(arguments);if(!a[0].isEmpty&&a[0].slot.hasOwnProperty("rendering")){var b=a[0].slot.getTargeting("sbi_size");0<b.length&&(b=b[0].split("x"),b=b.map(function(a){return parseInt(a,10)}),a[0].size=b);delete a[0].slot.rendering}c.apply(c,a)});f.apply(a.a,b)};var e=g.googletag.enableServices;g.googletag.enableServices=function(){var b=this,c=arguments;a.c.log("sbi",200031);a.g||(a.g=!0,a.h("initialized",a.w(),function(){e.apply(b,c);a.c.log("sbi",
200034,[a.$.toString()]);a.$.forEach(function(a){return g.googletag.display(a)});a.$=[]}))};var l=this.a.enableSingleRequest;this.a.enableSingleRequest=function(){a.g||(a.m.Oa=!0);l.apply(this,arguments)};this.a.disableInitialLoad=function(){a.g||(a.m.Na=!0)};var h=this.a.enableAsyncRendering;this.a.enableAsyncRendering=function(){a.g||(a.m.jb=!0);h.apply(this,arguments)}};t.prototype.Ya=function(a){return a.hasOwnProperty("isOutOfPage")&&a.isOutOfPage};D.prototype.w=function(a){this.i=a};D.prototype.m=
function(a){var b={};a=N(a);for(var c=a.next();!c.done;c=a.next()){var c=this.b.F(c.value),d=null,f;for(f in this.a)if(this.a[f].l==c){d=this.a[f].id;break}null!=d&&(b[d]=this.a[d])}return b};D.prototype.h=function(a){var b=this,c={},d={};a.forEach(function(a){var e=b.b.F(a),l=b.b.Ja(a);if(!(e in d)){c[l]=c[l]++||1;var h=C();d[h]={j:l,Cb:l+":"+c[l],l:e,id:h,Bb:!1,zb:!1,Z:!1,Ea:{},sa:[],ba:{},sizes:b.b.qa(a),Wa:{},yb:b.b.Ya(a),ia:b.b.qa.bind(b.b,a),fa:!1,wb:0}}});this.a=Object.assign(this.a,d)};D.prototype.ub=
function(a){for(var b in a)if(b in this.a){var c=this.a[b].l;this.a[b].ba=a[b];this.a[b].Wa=a[b].targeting;this.a[b].Wa.sbi_size=a[b].size;this.b.ab(c,a[b].targeting)}};Object.defineProperties(D.prototype,{B:{configurable:!0,enumerable:!0,get:function(){return this.a},set:function(a){this.a=a}}});I.prototype.ha=function(a){return a?this.a[a]:this.a};z.prototype.b=function(a,b){if(a){a=this.a[a];if(b){var c=a[b];r.Ca(b)&&!c?a=this.J.ha(b):a=c}return a}return this.a};w.prototype.Pa=function(a){var b=
a.key;a=this.b[a.u?a.u:this.u];if(b){var c=a[b];r.Ca(b)&&!c?a=this.a.b(r.Qa(this.a.b()),b):a=c}return a};w.prototype.Ra=function(a){var b=a.name;return this.h({u:void 0===a.u?this.u:a.u,ma:void 0===a.ma?"requestSettings":a.ma}).find(function(a){return a.name===b})};w.prototype.h=function(a){var b=[];a=this.b[void 0===a.u?this.u:a.u][void 0===a.ma?"requestSettings":a.ma]||[];for(var c=0;c<a.length;c++){var d=a[c];if(d.hasOwnProperty("dimensions")){var f="*";this.a.a&&(f=r.Qa(this.a.b()));var e;a:{e=
g.location.href;var l=r.Aa(d,"dimensions.domains")||[];if(0===l.length||-1<l.indexOf("*"))e=!0;else{for(var h=0;h<l.length;h++)if((new RegExp(l[h])).test(e)){e=!0;break a}e=!1}}e&&(e=r.Aa(d,"dimensions.platforms")||[],e="*"===f||0===e.length||-1<e.indexOf("*")?!0:-1<e.indexOf(f));e&&b.push(d)}else b.push(d)}return b};v.prototype.start=function(a,b,c){this.a||(this.c=c,a.Pa({}),this.X=a,this.a=!0,c.log("sbi",200011,[this.name]),this.b=this.Ga(a,b,c)||Promise.resolve({}));return this.b};v.prototype.lb=
function(a,b,c){var d=this,f=g.performance.now(),e,l=this.request(a,b,c).then(function(a){d.c.log("sbi",200010,[a]);f=Math.round(g.performance.now()-f);for(var b in a){a[b]||d.c.log("sbi",200014,[d.name]);for(var c=N(Array.from(a[b])),h=c.next();!h.done;h=c.next())h=h.value,h.la=!1,h.pb=f,h.Da?h.Sa=h.Da:h.Sa=f}a={v:!1,data:a,name:d.name,M:Promise.resolve({v:!1,data:a,name:d.name})};clearTimeout(e);return a}),h=d.X.Pa({key:"timeout"});a=new Promise(function(a){var b={v:!0,data:{},name:d.name,M:l};
e=setTimeout(function(){d.c.log("sbi",200013,[d.name,h]);a(b)},h)});return Promise.race([l,a])};q.prototype.clone=function(){return Object.assign(Object.create(this),this)};q.prototype.wa=function(a){var b=this.clone();switch(a){case 1:a={buyerid:b.P,buyername:b.da,adunit_code:b.O,pageViewId:b.U,bidid:b.ca,p:1,response:b.W,size:r.ua(b.C||"0x0"),s:b.C||"0x0",bid:b.V,latency:b.T,jsLatency:b.S};break;case 2:a={buyerid:b.P,buyername:b.da,adunit_code:b.O,pageViewId:b.U,bidid:b.ca,p:2,response:b.W,size:r.ua(b.C||
"0x0"),s:b.C||"0x0",bid:b.V,latency:b.T,jsLatency:b.S};b.I&&"string"==typeof b.I&&(a.dealid=b.ra);break;default:a={buyerid:b.P,buyername:b.da,adunit_code:b.O,pageViewId:b.U,bidid:b.ca,p:3,response:b.W,size:r.ua(b.C||"0x0"),s:b.C||"0x0",bid:b.V,latency:b.T,jsLatency:b.S}}return a};Object.defineProperties(q.prototype,{id:{configurable:!0,enumerable:!0,get:function(){return this.ca}},tb:{configurable:!0,enumerable:!0,get:function(){return this.U},set:function(a){this.U=a}},j:{configurable:!0,enumerable:!0,
get:function(){return this.w},set:function(a){this.w=a}},type:{configurable:!0,enumerable:!0,get:function(){return this.F},set:function(a){this.F=a}},eb:{configurable:!0,enumerable:!0,get:function(){return this.O},set:function(a){this.O=a}},f:{configurable:!0,enumerable:!0,get:function(){return this.V},set:function(a){this.V=a}},A:{configurable:!0,enumerable:!0,get:function(){return this.da}},Ta:{configurable:!0,enumerable:!0,get:function(){return this.h},set:function(a){this.h=a}},Sa:{configurable:!0,
enumerable:!0,get:function(){return this.T},set:function(a){this.T=a}},Da:{configurable:!0,enumerable:!0,get:function(){return this.i},set:function(a){this.i=a}},pb:{configurable:!0,enumerable:!0,get:function(){return this.S},set:function(a){this.S=a}},size:{configurable:!0,enumerable:!0,get:function(){return this.C},set:function(a){this.C=Array.isArray(a)?a.join("x"):a}},ta:{configurable:!0,enumerable:!0,get:function(){return this.P},set:function(a){this.P=a}},Ma:{configurable:!0,enumerable:!0,get:function(){return this.a},
set:function(a){this.a=a}},I:{configurable:!0,enumerable:!0,get:function(){return this.ra},set:function(a){this.ra=a}},Y:{configurable:!0,enumerable:!0,get:function(){return this.b},set:function(a){this.b=a}},response:{configurable:!0,enumerable:!0,get:function(){return this.W},set:function(a){this.W=a}},ka:{configurable:!0,enumerable:!0,get:function(){return this.m},set:function(a){this.m=a}},va:{configurable:!0,enumerable:!0,get:function(){return this.g},set:function(a){this.g=a}}});var ca={sonobi:new v({Ga:function(a,
b,c){this.X=a;this.aa=b;this.c=c;this.c.log("sbi",200022,["sonobi"])},request:function(a,b){var c=this,d={},f={},e;for(e in a){var l=a[e],h=l.j+"|"+encodeURIComponent(l.l);d[h]=l.sizes.join(",");f[h]=new q(l.sizes[0],"sonobi","sonobi",e,l.j,this.aa,b)}b=JSON.stringify(d);e=c.X.Ra({name:"cdf"})||[];l=c.X.Ra({name:"hfa"})||[];d="";e=N([].concat(e,l));for(l=e.next();!l.done;l=e.next())l=l.value,h=r.Aa(g,l.value),void 0!=h&&("object"===typeof h&&(h=JSON.stringify(h)),d+="&"+l.name+"="+encodeURIComponent(h));
e=location.protocol+"//apex.go.sonobi.com/trinity.js?key_maker=";var k=r.ya();b=e+b+d+"&cv=%%callback%%"+("&s="+k);c.c.log("sbi",200023,["sonobi",a]);return this.caller.qb(b).then(function(b){c.c.log("sbi",200024,["sonobi",a,b]);var d=r.mb(k);return c.parse.call(c,b,a,d,f)})},parse:function(a,b,c,d){var f={},e;for(e in b){var l=b[e],h=l.j+"|"+l.l,g=l.j+"|"+encodeURIComponent(l.l);h in a.slots&&(g=d[g],h=a.slots[h],"sbi_aid"in h||(h={sbi_aid:null,sbi_apoc:null,sbi_size:null}),"sbi_dozer"in h||(h.sbi_dozer=
!1),"sbi_pri"in h||(h.sbi_pri=10),"sbi_mouse"in h||(h.sbi_mouse=0,h.sbi_pri=1),"outstream"==h.sbi_size&&(h.sbi_size="1x1",g.type=1),g.f=100*parseFloat(h.sbi_mouse),g.size=h.sbi_size||g.size,g.I=h.sbi_dozer,g.Y=parseInt(h.sbi_pri,10),g.Da=c,g.Ta={sbi_aid:h.sbi_aid,sbi_dc:a.sbi_dc},g.Ma=r.ib("//%%sbi_dc%%apex.go.sonobi.com/sbi.js?aid=%%sbi_aid%%&as=null","SCRIPT"),g.eb=l.j,1===parseInt(h.sbi_pri,10)?(g.ka=[{ge:0,set:h.sbi_dozer}],g.Ua="sbi_dozer"):h.sbi_dozer&&(g.va={sbi_dozer:h.sbi_dozer}),f[l.id]=
[g])}this.c.log("sbi",200025,["sonobi",b,f]);return f},name:"sonobi",ta:"sonobi"})};p.prototype.Fa=function(a,b,c,d){var f=this,e=this;this.c.log("sbi",200001,[c]);this.c.log("sbi",200006);var g=[],h={},k=!1;b.adapterSettings.forEach(function(c){var m=c.name;if(!c.disabled){c=c.sizes;e.c.log("sbi",200011,[m]);var p={},n;for(n in a)if(a.hasOwnProperty(n)){a[n].sizes=a[n].ia();var q=W(a[n].sizes,c);0<q.length&&(p[n]=Object.assign({},a[n]),p[n].sizes=q)}0<Object.keys(p).length?(n=ca[m].start(new w(b,
m),f.aa,f.c),g.push(n.then(function(a){return ca[m].lb(p,d,a).then(function(a){if(!k&&!a.v)for(var b in a.data)a.data[b].forEach(function(a){a.za=!1;a.v=!1;h[a.id]=a},e);a.M.then(function(a){for(var b in a.data)a.data[b].forEach(function(b){b.za=k;b.v=a.v;b.v&&e.c.log("sbi",200008,[m]);k&&a.v&&(h[b.id]=b)},e)});return a})}))):g.push(new Promise(function(a){a({})}))}});var m,p=Promise.all(g).then(function(){if(!k)return clearTimeout(m),e.a=Object.assign(e.a,h),k=!0,h}),n=new Promise(function(a){e.c.log("sbi",
200002);m=setTimeout(function(){e.c.log("sbi",200009);e.a=Object.assign(e.a,h);k=!0;a(h)},c)});return Promise.race([p,n])};p.prototype.nb=function(a,b){a=a.filter(function(a){return!a.v&&!a.za});if(0==a.length)return{};var c={};a.forEach(function(a){c[a.j]=c[a.j]||[];c[a.j]=c[a.j].concat(a)});a={};for(var d in c){var e=ba.sonobiDealWinsOverHighestCPM(c[d],this.c);if(null!=e){e.Ia=!0;a[d]={targeting:{}};a[d].id=e.id;a[d].targeting.sbi_kmid=d;a[d].targeting.sbi_bidder=e.A;var g="sbi_price";null!=e.Ua&&
(g=e.Ua);Array.isArray(e.ka)&&0<e.ka.length&&(b=e.ka);a[d].targeting[g]=Y(e.f,b);for(var l in e.va)a[d].targeting[l]=e.va[l];g=e.Ma;g=aa(g,e.Ta,"%%");a[d].creative=g;a[d].size=e.size}}this.c.log("sbi",200005,[a]);return a};Object.defineProperties(p.prototype,{sa:{configurable:!0,enumerable:!0,get:function(){return this.a},set:function(a){this.a=a}}});k.prototype.ea=function(a){var b=this;this.a.length||setTimeout(function(){b.b(b.a,void 0,void 0);b.a=[]},100);this.a.push(a)};k.prototype.i=function(a,
b){var c=0;a.hb&&(c|=16);a.vb&&(c|=8);a.Ia&&(c|=4);a.la&&(c|=2);a.Ba&&(c|=1);switch(c){case 0:return 1;case 8:return 0;case 16:return 4;case 17:return 4;case 20:case 21:return this.c.log("sbi",200018,[b.f,b.A]),5;case 22:case 23:return 6;case 24:return 2;case 25:return this.c.log("sbi",200016),3;default:throw Error("Invalid bid status: "+c.toString(2)||"Assertion failed!");}};k.prototype.h=function(a){var b={f:0};a=N(a);for(var c=a.next();!c.done;c=a.next())c=c.value,c.f>b.f&&(b=c);b.Ba=!0};k.prototype.fb=
function(a){this.h(a);a=N(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;this.c.log("sbi",200026,[b.A,b]);var c={hb:0<b.f,vb:b.za||b.v,Ia:b.Ia,la:b.la,Ba:b.Ba},d=void 0;try{d=this.i(c,b),b.response=d}catch(e){this.c.log(200020,[e.message]);continue}this.ea(b.wa(2))}};k.prototype.b=function(a,b,c){b=void 0===b?this.g.gb.kb():b;c=void 0===c?r.ya():c;a=r.ob(a,"pageViewId");var d={},e;for(e in a){d.oa=e;d.H=a[d.oa];for(var g=function(a){return function(){var c=a.oa;a.H.forEach(function(a){delete a.tb});
return b+"?pageviewid="+c+"&data="+JSON.stringify(a.H)}}(d),l=g(),h=l.length,k=[];2E3<h+b.length;){k.push(d.H.splice(0,1)[0]);if(0==d.H.length)break;l=g();h=l.length}2E3>=l.length&&this.caller.a(l);0<k.length&&this.b(k,b,c);d={oa:d.oa,H:d.H}}};m.prototype.kb=function(){var a=this.a.url;r.Ca("url")&&!a&&(a=this.J.ha("url"));return a};n.prototype.a=function(a){a.adapterSettings.forEach(function(a){!a.hasOwnProperty("frequency")||Math.random()<=a.frequency&&!1===a.disabled||(a.disabled=!0)})};g.sbi_morpheus=
{registration:{},register:function(){},enableReactiveSizes:function(){},callOperator:function(){},cmd:[]};g.sbi_km=g.sbi_km||{};g.sbi_km.API=g.sbi_km.API||{};g.sbi_km.config=e;g.addEventListener("message",function(a){"SAFE_FRAME_RENDER"===a.data.key&&g.sbi_km.API.render(a.source,a.data.id,a.data.macros,!0)},!1);var Q=new n(e),H=new G(e),R=new k(H,Q),da=new p(H,R),ea=new D(H,0,da,R);ea.w(function(a,b,c,d,e,g){return{Fa:function(k,h){if(Object.keys(k).length){var m=C();a.Fa(k,b,c,m).then(function(b){var c=
Object.keys(b).map(function(a){return b[a]});c.length?(d.ub(a.nb(c,e.J.ha("priceRules")||[])),c=c.map(function(a){return a.clone()}),c.length&&(c=c.map(function(a){a.j=k[a.j].j;return a}),g.fb(c),h())):h()})}}}}(da,e,Q.J.ha("timeout"),ea,Q,R).Fa);g.sbi_km.API.debug=H.h.bind(H);-1===g.location.search.indexOf("sbi_test")?document.cookie="sbi_debug=false":-1!==document.cookie.indexOf("sbi_debug=true")?g.sbi_km.API.debug(!0):-1!==g.location.search.indexOf("sbi_test")&&(document.cookie="sbi_debug=true",
g.sbi_km.API.debug(!0))}).call(this,window.sbi_config||{adapterSettings:[{requestSettings:[],platforms:["mobile","desktop","tablet"],sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),timeout:2500,disabled:!1,name:"sonobi"}],platformSettings:{desktop:{viewport:{ge:992}},tablet:{viewport:{ge:768,lt:992}},mobile:{viewport:{lt:768}}},globalSettings:{timeout:1600,priceRules:[{set:2E3,ge:2E3},{round:5,ge:900,lt:2E3},{round:1,ge:0,lt:900}],
sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" ")},analyticsSettings:{timeout:2E3,url:"https://keymaker.go.sonobi.com/keymaker"},url:"//mtrx.go.sonobi.com",adServer:"dfp"});window.sbi_km.version="3.5.4";}).call(window)
